/*
 * simulation_physics_single_file.js
 * Single-file physics reference for inspection.
 * Generated by concatenating physics.js and rocket_physics.js.
 */

/**
 * ============================================================================
 * physics.js — Pure Physics Engine for Matilda's Cannon Lab
 * ============================================================================
 *
 * ROLE:  All physics calculations live here. Every function is PURE — it takes
 *        inputs and returns outputs with zero side-effects, zero DOM access.
 *
 * EXPORTS (via window.Physics namespace):
 *   computeLaunchVelocity(force, mass, barrelLength) → speed (m/s)
 *   createProjectile(x, y, speed, angleDeg, mass)    → state object
 *   stepProjectile(state, dt, gravity)                → new state object
 *   computeEnergy(state, gravity)                     → { ke, pe, tme }
 *
 * LOADED BY: <script src="physics.js"> in index.html (before renderer/ui/main)
 * ============================================================================
 */

(function () {
  'use strict';

  // ── Constants ──────────────────────────────────────────────────────────────
  var BARREL_LENGTH = 2.0; // metres — tunable, kept here as engine default

  // ── Helpers ────────────────────────────────────────────────────────────────
  function degToRad(deg) {
    return deg * Math.PI / 180;
  }

  // ── Core API ───────────────────────────────────────────────────────────────

  /**
   * Work-energy theorem:  ½mv² = F·d   →   v = √(2Fd / m)
   * @param {number} force        Applied force in Newtons
   * @param {number} mass         Mass in kg
   * @param {number} barrelLength Optional override (default 2.0 m)
   * @returns {number} Launch speed in m/s
   */
  function computeLaunchVelocity(force, mass, barrelLength) {
    var d = (typeof barrelLength === 'number') ? barrelLength : BARREL_LENGTH;
    if (mass <= 0) return 0;

    // Clamp invalid/negative inputs so we never take sqrt of a negative value.
    var F = isFinite(force) ? Math.max(0, force) : 0;
    d = isFinite(d) ? Math.max(0, d) : 0;
    var workPerMass = (2 * F * d) / mass;
    if (workPerMass <= 0) return 0;

    return Math.sqrt(workPerMass);
  }

  /**
   * Build an initial projectile state from cannon parameters.
   * Physics coordinates: +x right, +y UP (metres).
   *
   * @param {number} x0       Launch x in metres
   * @param {number} y0       Launch y in metres (height above ground)
   * @param {number} speed    Launch speed (from computeLaunchVelocity)
   * @param {number} angleDeg Barrel angle in degrees from horizontal
   * @param {number} mass     Ball mass in kg
   * @returns {object} Projectile state
   */
  function createProjectile(x0, y0, speed, angleDeg, mass) {
    var rad = degToRad(angleDeg);
    return {
      x: x0,
      y: y0,
      vx: speed * Math.cos(rad),
      vy: speed * Math.sin(rad),
      mass: mass,
      time: 0,
      launched: true
    };
  }

  /**
   * Advance projectile by dt seconds (Euler integration).
   * Returns a NEW state object — original is untouched.
   *
   * @param {object} state   Current projectile state
   * @param {number} dt      Delta-time in seconds
   * @param {number} gravity Gravity magnitude m/s² (positive number)
   * @returns {object} New state
   */
  function stepProjectile(state, dt, gravity) {
    var newVx = state.vx;                  // ax = 0
    var newVy = state.vy - gravity * dt;   // ay = -g  (y-up convention)

    return {
      x: state.x + newVx * dt,
      y: state.y + 0.5 * (state.vy + newVy) * dt, // velocity-Verlet: exact for constant g
      vx: newVx,
      vy: newVy,
      mass: state.mass,
      time: state.time + dt,
      launched: true
    };
  }

  /**
   * Compute kinetic, potential, and total mechanical energy.
   *
   * @param {object} state   Projectile state (needs vx, vy, mass, y)
   * @param {number} gravity Gravity magnitude (m/s²)
   * @returns {{ ke: number, pe: number, tme: number }}
   */
  function computeEnergy(state, gravity) {
    var speedSq = state.vx * state.vx + state.vy * state.vy;
    var ke = 0.5 * state.mass * speedSq;
    var pe = state.mass * gravity * Math.max(state.y, 0);
    return { ke: ke, pe: pe, tme: ke + pe };
  }

  /**
   * Compute the current speed scalar.
   * @param {object} state
   * @returns {number} speed in m/s
   */
  function speed(state) {
    return Math.sqrt(state.vx * state.vx + state.vy * state.vy);
  }

  /**
   * Predict full trajectory analytically (for zoom planning).
   * Returns range, max height, flight time.
   */
  function predictTrajectory(force, mass, angleDeg, gravity, startX, startY, barrelLength) {
    var spd = computeLaunchVelocity(force, mass, barrelLength);
    var rad = degToRad(angleDeg);
    var vx = spd * Math.cos(rad);
    var vy = spd * Math.sin(rad);

    // Time to hit ground: startY + vy*t - 0.5*g*t² = 0
    var disc = vy * vy + 2 * gravity * startY;
    var flightTime = (vy + Math.sqrt(Math.max(0, disc))) / gravity;
    var range = startX + vx * flightTime;
    // Only upward vertical velocity contributes to a higher apex.
    var vyUp = Math.max(0, vy);
    var maxHeight = startY + (vyUp * vyUp) / (2 * gravity);

    return {
      range: range,
      maxHeight: maxHeight,
      flightTime: flightTime,
      launchSpeed: spd
    };
  }

  // ── Expose namespace ──────────────────────────────────────────────────────
  window.Physics = {
    BARREL_LENGTH: BARREL_LENGTH,
    computeLaunchVelocity: computeLaunchVelocity,
    createProjectile: createProjectile,
    stepProjectile: stepProjectile,
    computeEnergy: computeEnergy,
    predictTrajectory: predictTrajectory,
    speed: speed,
    degToRad: degToRad
  };

})();
/**
 * ============================================================================
 * rocket_physics.js — Continuous-Thrust Rocket Physics Engine
 * ============================================================================
 *
 * ROLE:  All rocket-mode physics calculations. Every function is PURE — takes
 *        inputs and returns outputs with zero side-effects, zero DOM access.
 *        Implements the golden-path per-timestep algorithm from
 *        rocket_lab_single_source_of_truth.md Section 13.
 *
 * DEPENDS ON: rocket_propellants.js (for performance lookup)
 *
 * EXPORTS (via window.RocketPhysics namespace):
 *
 *   Core propulsion:
 *     computeMassFlow(Pc_Pa, At, cStarEff)        → ṁ (kg/s)
 *     computeThrust(CfEff, Pc_Pa, At)             → F (N)
 *     computeIsp(F, mdot, g0)                     → Isp (s)
 *     computeExhaustVelocity(Isp, g0)             → ve (m/s)
 *
 *   Vehicle:
 *     createRocketState(config)                    → initial state object
 *     stepRocket(state, dt, gravity, guidance)     → new state object
 *
 *   Guidance:
 *     guidanceFixed(theta0)                        → guidance object (Mode A)
 *     guidancePitchProgram(theta0, thetaF, t1, t2) → guidance object (Mode B)
 *     guidanceProgradeLock(vMin, fallbackTheta)    → guidance object (Mode C)
 *     buildGuidance(config)                         → guidance from UI config
 *
 *   Derived helpers:
 *     computeDeltaV(Isp, m0, mf, g0)              → Δv (m/s)
 *     computeThrustToWeight(F, m0, g)              → T/W ratio
 *     computeBurnTime(mProp, mdot)                 → t_burn (s)
 *     solveThroatForThrust(Ftarget, CfEff, Pc_Pa) → At (m²)
 *     throatAreaFromDiameter(d_mm)                 → At (m²)
 *     predictTrajectory(config, gravity, options)  → predicted full flight envelope
 *
 * LOADED BY: <script src="rocket_physics.js"> in index.html
 *            (after rocket_propellants.js, before main.js)
 * ============================================================================
 */

(function () {
  'use strict';

  // ── Constants ──────────────────────────────────────────────────────────────
  var G0 = 9.80665; // standard gravity (m/s²)
  var DEG_TO_RAD = Math.PI / 180;
  var RAD_TO_DEG = 180 / Math.PI;

  // ── Core propulsion equations (Section 3 of spec) ──────────────────────────

  /**
   * Mass flow rate through a choked throat.
   *   ṁ = pc · At / c*_eff
   *
   * @param {number} Pc_Pa     Chamber pressure (Pa)
   * @param {number} At        Throat area (m²)
   * @param {number} cStarEff  Effective characteristic velocity (m/s)
   * @returns {number} Mass flow rate (kg/s)
   */
  function computeMassFlow(Pc_Pa, At, cStarEff) {
    if (cStarEff <= 0) return 0;
    return (Pc_Pa * At) / cStarEff;
  }

  /**
   * Thrust from effective Cf, chamber pressure, and throat area.
   *   F = Cf_eff · pc · At
   *
   * @param {number} CfEff  Effective thrust coefficient
   * @param {number} Pc_Pa  Chamber pressure (Pa)
   * @param {number} At     Throat area (m²)
   * @returns {number} Thrust (N)
   */
  function computeThrust(CfEff, Pc_Pa, At) {
    return CfEff * Pc_Pa * At;
  }

  /**
   * Specific impulse.
   *   Isp = F / (ṁ · g0)
   *
   * @param {number} F    Thrust (N)
   * @param {number} mdot Mass flow rate (kg/s)
   * @param {number} [g0] Standard gravity (default 9.80665)
   * @returns {number} Isp (s)
   */
  function computeIsp(F, mdot, g0) {
    g0 = g0 || G0;
    if (mdot <= 0) return 0;
    return F / (mdot * g0);
  }

  /**
   * Exhaust velocity.
   *   ve = g0 · Isp
   *
   * @param {number} Isp  Specific impulse (s)
   * @param {number} [g0] Standard gravity (default 9.80665)
   * @returns {number} Exhaust velocity (m/s)
   */
  function computeExhaustVelocity(Isp, g0) {
    g0 = g0 || G0;
    return g0 * Isp;
  }

  // ── Derived helpers ────────────────────────────────────────────────────────

  /**
   * Tsiolkovsky rocket equation.
   *   Δv = ve · ln(m0/mf) = g0 · Isp · ln(m0/mf)
   *
   * @param {number} Isp  Specific impulse (s)
   * @param {number} m0   Initial mass (kg)
   * @param {number} mf   Final (dry) mass (kg)
   * @param {number} [g0] Standard gravity
   * @returns {number} Delta-v (m/s)
   */
  function computeDeltaV(Isp, m0, mf, g0) {
    g0 = g0 || G0;
    if (mf <= 0 || m0 <= mf) return 0;
    return g0 * Isp * Math.log(m0 / mf);
  }

  /**
   * Thrust-to-weight ratio.
   *   T/W = F / (m0 · g)
   *
   * @param {number} F   Thrust (N)
   * @param {number} m0  Vehicle mass (kg)
   * @param {number} g   Local gravity (m/s²)
   * @returns {number} T/W ratio (dimensionless)
   */
  function computeThrustToWeight(F, m0, g) {
    if (m0 <= 0 || g <= 0) return 0;
    return F / (m0 * g);
  }

  /**
   * Estimated burn time (constant thrust).
   *   t_burn = mProp / ṁ
   *
   * @param {number} mProp  Propellant mass (kg)
   * @param {number} mdot   Mass flow rate (kg/s)
   * @returns {number} Burn time (s)
   */
  function computeBurnTime(mProp, mdot) {
    if (mdot <= 0) return Infinity;
    return mProp / mdot;
  }

  /**
   * Solve for throat area given a target thrust.
   *   At = F / (Cf_eff · pc)
   *
   * @param {number} Ftarget  Desired thrust (N)
   * @param {number} CfEff    Effective thrust coefficient
   * @param {number} Pc_Pa    Chamber pressure (Pa)
   * @returns {number} Throat area (m²)
   */
  function solveThroatForThrust(Ftarget, CfEff, Pc_Pa) {
    if (CfEff <= 0 || Pc_Pa <= 0) return 0;
    return Ftarget / (CfEff * Pc_Pa);
  }

  /**
   * Convert throat diameter in mm to throat area in m².
   *
   * @param {number} d_mm  Throat diameter (mm)
   * @returns {number} Throat area (m²)
   */
  function throatAreaFromDiameter(d_mm) {
    var r = (d_mm / 1000) / 2; // radius in metres
    return Math.PI * r * r;
  }

  // ── Guidance modes (Section 5 of spec) ─────────────────────────────────────
  //
  // Each guidance function returns an object with a `getAngle(state)` method
  // that computes the current thrust angle in DEGREES given the rocket state.
  //

  /**
   * Mode A: Fixed angle — thrust direction is constant.
   *
   * @param {number} theta0  Fixed thrust angle (degrees from +x axis)
   * @returns {{ mode: string, getAngle: function }}
   */
  function guidanceFixed(theta0) {
    return {
      mode: 'fixed',
      getAngle: function (/* state */) {
        return theta0;
      }
    };
  }

  /**
   * Mode B: Pitch program — linear ramp from theta0 to thetaF between t1 and t2.
   *   θ(t) = θ0 + (θf − θ0) · clamp((t − t1) / (t2 − t1), 0, 1)
   *
   * @param {number} theta0  Start angle (deg)
   * @param {number} thetaF  End angle (deg)
   * @param {number} t1      Ramp start time (s)
   * @param {number} t2      Ramp end time (s)
   * @returns {{ mode: string, getAngle: function }}
   */
  function guidancePitchProgram(theta0, thetaF, t1, t2) {
    return {
      mode: 'pitch_program',
      getAngle: function (state) {
        var t = state.time;
        if (t2 <= t1) return theta0;
        var frac = (t - t1) / (t2 - t1);
        frac = Math.max(0, Math.min(1, frac)); // clamp
        return theta0 + (thetaF - theta0) * frac;
      }
    };
  }

  /**
   * Mode C: Prograde lock — orient thrust along velocity vector once speed
   * exceeds vMin. Falls back to fixed angle when speed is below threshold.
   *
   * @param {number} vMin          Speed threshold (m/s)
   * @param {number} fallbackTheta Fallback angle (deg) when speed < vMin
   * @returns {{ mode: string, getAngle: function }}
   */
  function guidanceProgradeLock(vMin, fallbackTheta) {
    return {
      mode: 'prograde_lock',
      getAngle: function (state) {
        var speed = Math.sqrt(state.vx * state.vx + state.vy * state.vy);
        if (speed < vMin) return fallbackTheta;
        return Math.atan2(state.vy, state.vx) * RAD_TO_DEG;
      }
    };
  }

  /**
   * Build a guidance object directly from the user config shape.
   *
   * @param {Object} config  Same object used by createRocketState/getRocketValues
   * @returns {{ mode: string, getAngle: function }}
   */
  function buildGuidance(config) {
    if (config.guidanceMode === 'pitch_program') {
      return guidancePitchProgram(
        config.launchAngle,
        config.pitchEnd,
        config.pitchT1,
        config.pitchT2
      );
    }
    if (config.guidanceMode === 'prograde_lock') {
      var vMin = (config.progradeVmin !== undefined) ? config.progradeVmin : 10;
      return guidanceProgradeLock(vMin, config.launchAngle);
    }
    // 'fixed' in UI currently means "gravity turn" behaviour.
    return guidanceProgradeLock(5, config.launchAngle);
  }

  // ── Rocket state creation ──────────────────────────────────────────────────

  /**
   * Create an initial rocket state object from user config.
   *
   * @param {Object} config
   *   propellantId  {string}  Propellant registry ID (e.g. 'LOX_RP1')
   *   MR            {number}  Mixture ratio O/F
   *   Pc_bar        {number}  Chamber pressure (bar)
   *   epsilon       {number}  Expansion ratio (Ae/At)
   *   throatDia_mm  {number}  Throat diameter (mm)
   *   dryMass       {number}  Dry mass (kg)
   *   propMass      {number}  Propellant mass (kg)
   *   launchAngle   {number}  Launch angle (degrees from horizontal)
   *   etaC          {number}  Combustion efficiency (0–1, default 0.95)
   *   etaN          {number}  Nozzle efficiency (0–1, default 0.95)
   *   Pa_Pa         {number}  Ambient pressure (Pa, default 101325)
   * @returns {Object} Rocket state
   */
  function createRocketState(config) {
    var At = throatAreaFromDiameter(config.throatDia_mm);
    var Pc_Pa = config.Pc_bar * 1e5; // bar → Pa
    var etaC = (config.etaC !== undefined) ? config.etaC : 0.95;
    var etaN = (config.etaN !== undefined) ? config.etaN : 0.95;
    var Pa_Pa = (config.Pa_Pa !== undefined) ? config.Pa_Pa : 101325;

    // Look up performance at initial conditions
    var perf = RocketPropellants.lookupPerformance(
      config.propellantId, config.MR, Pc_Pa, config.epsilon, Pa_Pa
    );

    var cStarEff = etaC * perf.cStar;
    var CfEff = etaN * perf.Cf;
    var mdot = computeMassFlow(Pc_Pa, At, cStarEff);
    var F = computeThrust(CfEff, Pc_Pa, At);
    var Isp = computeIsp(F, mdot);
    var m0 = config.dryMass + config.propMass;

    return {
      // Position (metres, physics coords: +x right, +y up)
      x: 0,
      y: 0,

      // Velocity (m/s)
      vx: 0,
      vy: 0,

      // Masses (kg)
      mDry: config.dryMass,
      mProp: config.propMass,
      mPropInitial: config.propMass,

      // Engine config (carried for recomputation each step)
      propellantId: config.propellantId,
      MR: config.MR,
      Pc_Pa: Pc_Pa,
      epsilon: config.epsilon,
      At: At,
      etaC: etaC,
      etaN: etaN,
      Pa_Pa: Pa_Pa,

      // Engine state
      engineOn: true,

      // Current computed values (updated each step)
      thrustMagnitude: F,
      mdot: mdot,
      Isp: Isp,

      // Guidance
      theta: config.launchAngle, // current thrust angle (deg from +x)

      // Timing / accumulators
      time: 0,
      totalImpulse: 0,

      // Status flags
      launched: false,
      fizzled: false,

      // Mass (total, for convenience)
      mass: m0
    };
  }

  // ── Golden-path per-timestep update (Section 13 of spec) ───────────────────

  /**
   * Advance rocket state by one timestep.
   * Returns a NEW state object — original is untouched.
   *
   * @param {Object} state     Current rocket state
   * @param {number} dt        Timestep (seconds)
   * @param {number} gravity   Local gravity magnitude (m/s², positive)
   * @param {Object} guidance  Guidance object from guidanceFixed/PitchProgram/ProgradeLock
   * @returns {Object} New rocket state
   */
  function stepRocket(state, dt, gravity, guidance) {
    // Clone state (shallow copy — all fields are primitives)
    var s = {};
    for (var k in state) {
      if (state.hasOwnProperty(k)) s[k] = state[k];
    }
    s.time += dt;

    // ── 1) Guidance → compute θ ──
    s.theta = guidance.getAngle(s);
    var thetaRad = s.theta * DEG_TO_RAD;

    // ── 2) Engine ──
    var F = 0;
    var mdot = 0;
    var Isp = 0;
    var thrustScale = 1;

    if (s.engineOn && s.mProp > 0) {
      // Look up current c* and Cf
      var perf = RocketPropellants.lookupPerformance(
        s.propellantId, s.MR, s.Pc_Pa, s.epsilon, s.Pa_Pa
      );

      var cStarEff = s.etaC * perf.cStar;
      var CfEff = s.etaN * perf.Cf;

      mdot = computeMassFlow(s.Pc_Pa, s.At, cStarEff);
      F = computeThrust(CfEff, s.Pc_Pa, s.At);
      Isp = computeIsp(F, mdot);

      // Deplete propellant
      var consumed = mdot * dt;
      if (consumed >= s.mProp) {
        // Propellant exhausted this step — pro-rate
        var dtActual = s.mProp / mdot;
        consumed = s.mProp;
        // Apply only the burn fraction of thrust to this step's kinematics.
        thrustScale = (dt > 0) ? (dtActual / dt) : 0;
        thrustScale = Math.max(0, Math.min(1, thrustScale));

        // Scale impulse contribution
        s.totalImpulse += F * dtActual;
        s.mProp = 0;
        s.engineOn = false;
      } else {
        s.mProp -= consumed;
        s.totalImpulse += F * dt;
      }
    }

    var effectiveThrust = F * thrustScale;
    s.thrustMagnitude = effectiveThrust;
    s.mdot = mdot;
    s.Isp = Isp;

    // ── 3) Mass ──
    s.mass = s.mDry + s.mProp;

    // ── 4) Acceleration ──
    var ax, ay;
    if (s.mass > 0 && effectiveThrust > 0) {
      ax = (effectiveThrust / s.mass) * Math.cos(thetaRad);
      ay = (effectiveThrust / s.mass) * Math.sin(thetaRad) - gravity;
    } else {
      ax = 0;
      ay = -gravity;
    }

    // ── Fizzle check ──
    // On the very first step (not yet launched), check T/W.
    // If thrust cannot overcome weight, the rocket fizzles on the pad.
    if (!state.launched && !state.fizzled) {
      var tw = computeThrustToWeight(F, s.mass, gravity);
      if (tw < 1.0) {
        // Fizzle: rocket never lifts off
        s.fizzled = true;
        s.engineOn = false;
        s.vx = 0;
        s.vy = 0;
        s.x = 0;
        s.y = 0;
        s.thrustMagnitude = F; // keep last thrust for readouts
        return s;
      }
      s.launched = true;
    }

    // If already fizzled, don't move
    if (s.fizzled) {
      return s;
    }

    // ── 5) Semi-implicit Euler integration ──
    // v += a·dt
    s.vx += ax * dt;
    s.vy += ay * dt;
    // r += v·dt  (using updated velocity)
    s.x += s.vx * dt;
    s.y += s.vy * dt;

    // ── 7) Ground impact check ──
    if (s.y <= 0 && s.vy < 0) {
      // Interpolate exact impact x only when crossing from above ground.
      if (state.y > 0 && state.y !== s.y) {
        var alpha = state.y / (state.y - s.y);
        s.x = state.x + alpha * (s.x - state.x);
      } else {
        s.x = state.x;
      }
      s.y = 0;
      s.vy = 0;
      s.vx = 0; // stopped
      s.engineOn = false;
    }

    return s;
  }

  // ── Pre-launch computation helpers ─────────────────────────────────────────
  //
  // These compute what the UI needs to show in the pre-launch readouts
  // WITHOUT creating or stepping a rocket state.

  /**
   * Compute all pre-launch readouts from user config + gravity.
   *
   * @param {Object} config  Same shape as createRocketState config
   * @param {number} gravity Local gravity (m/s²)
   * @returns {Object} { thrust, mdot, Isp, tw, burnTime, deltaV, ve, m0 }
   */
  function computePreLaunch(config, gravity) {
    var At = throatAreaFromDiameter(config.throatDia_mm);
    var Pc_Pa = config.Pc_bar * 1e5;
    var etaC = (config.etaC !== undefined) ? config.etaC : 0.95;
    var etaN = (config.etaN !== undefined) ? config.etaN : 0.95;
    var Pa_Pa = (config.Pa_Pa !== undefined) ? config.Pa_Pa : 101325;

    var perf = RocketPropellants.lookupPerformance(
      config.propellantId, config.MR, Pc_Pa, config.epsilon, Pa_Pa
    );

    var cStarEff = etaC * perf.cStar;
    var CfEff = etaN * perf.Cf;
    var mdot = computeMassFlow(Pc_Pa, At, cStarEff);
    var F = computeThrust(CfEff, Pc_Pa, At);
    var Isp = computeIsp(F, mdot);
    var ve = computeExhaustVelocity(Isp);
    var m0 = config.dryMass + config.propMass;
    var mf = config.dryMass;
    var tw = computeThrustToWeight(F, m0, gravity);
    var burnTime = computeBurnTime(config.propMass, mdot);
    var deltaV = computeDeltaV(Isp, m0, mf);

    return {
      thrust: F,
      mdot: mdot,
      Isp: Isp,
      ve: ve,
      tw: tw,
      burnTime: burnTime,
      deltaV: deltaV,
      m0: m0,
      cStar: cStarEff,
      Cf: CfEff,
      At: At,
      Pc_Pa: Pc_Pa
    };
  }

  /**
   * Numerically predict the complete rocket trajectory from initial settings.
   * Uses the SAME stepRocket integrator as live flight, but at fixed dt.
   *
   * @param {Object} config   Same shape as createRocketState config
   * @param {number} gravity  Local gravity (m/s²)
   * @param {Object} [options]
   *   guidance  {Object} Pre-built guidance object (optional)
   *   dt        {number} Fixed simulation step in seconds (default 1/120)
   *   maxTime   {number} Max simulated seconds before bailing out (default 600)
   *   startX    {number} Launch x position in metres (default 0)
   *   startY    {number} Launch y position in metres (default 0)
   * @returns {Object}
   *   {
   *     fizzled, complete, time, burnTime,
   *     launchX, launchY,
   *     minX, maxX, maxHeight,
   *     downrange, flightTime,
   *     landingX, landingY
   *   }
   */
  function predictTrajectory(config, gravity, options) {
    options = options || {};

    var dt = (options.dt && options.dt > 0) ? options.dt : (1 / 120);
    var maxTime = (options.maxTime && options.maxTime > 0) ? options.maxTime : 600;
    var launchX = (typeof options.startX === 'number') ? options.startX : 0;
    var launchY = (typeof options.startY === 'number') ? options.startY : 0;
    var guidance = options.guidance || buildGuidance(config);

    var state = createRocketState(config);
    state.x = launchX;
    state.y = launchY;

    var minX = launchX;
    var maxX = launchX;
    var maxHeight = Math.max(0, launchY);
    var burnTime = 0;
    var complete = false;

    var maxSteps = Math.max(1, Math.ceil(maxTime / dt));
    for (var i = 0; i < maxSteps; i++) {
      var engineWasOn = state.engineOn;
      state = stepRocket(state, dt, gravity, guidance);

      if (state.fizzled) {
        return {
          fizzled: true,
          complete: true,
          time: state.time,
          burnTime: 0,
          launchX: launchX,
          launchY: launchY,
          minX: launchX,
          maxX: launchX,
          maxHeight: Math.max(0, launchY),
          downrange: 0,
          flightTime: 0,
          landingX: launchX,
          landingY: launchY
        };
      }

      if (state.x < minX) minX = state.x;
      if (state.x > maxX) maxX = state.x;
      if (state.y > maxHeight) maxHeight = state.y;

      if (engineWasOn && !state.engineOn && burnTime === 0) {
        burnTime = state.time;
      }

      // Guard against pathological settings producing non-finite states.
      if (!isFinite(state.x) || !isFinite(state.y) ||
          !isFinite(state.vx) || !isFinite(state.vy)) {
        break;
      }

      if (state.y <= 0 && state.vy <= 0 && state.time > 0.2) {
        complete = true;
        break;
      }
    }

    if (burnTime === 0 && !state.engineOn) {
      burnTime = state.time;
    }

    return {
      fizzled: false,
      complete: complete,
      time: state.time,
      burnTime: burnTime,
      launchX: launchX,
      launchY: launchY,
      minX: minX,
      maxX: maxX,
      maxHeight: Math.max(0, maxHeight),
      downrange: Math.max(0, state.x - launchX),
      flightTime: state.time,
      landingX: state.x,
      landingY: Math.max(0, state.y)
    };
  }

  // ── Expose namespace ───────────────────────────────────────────────────────
  window.RocketPhysics = {
    // Constants
    G0: G0,

    // Core propulsion
    computeMassFlow: computeMassFlow,
    computeThrust: computeThrust,
    computeIsp: computeIsp,
    computeExhaustVelocity: computeExhaustVelocity,

    // Vehicle
    createRocketState: createRocketState,
    stepRocket: stepRocket,

    // Guidance
    guidanceFixed: guidanceFixed,
    guidancePitchProgram: guidancePitchProgram,
    guidanceProgradeLock: guidanceProgradeLock,
    buildGuidance: buildGuidance,

    // Tsiolkovsky comparator
    computeDeltaV: computeDeltaV,

    // Derived helpers
    computeThrustToWeight: computeThrustToWeight,
    computeBurnTime: computeBurnTime,
    solveThroatForThrust: solveThroatForThrust,
    throatAreaFromDiameter: throatAreaFromDiameter,

    // Pre-launch computation
    computePreLaunch: computePreLaunch,
    predictTrajectory: predictTrajectory
  };

})();
