export const NOZZLE_TOPICS = {
  propellant:{name:'Propellant pair',tip:'Propellant means fuel plus oxidiser. Change the pair to compare how much push each kilogram can provide. This teaching model leaves out tank size, cooling and cost.',levels:[
    ['Two ingredients, one journey.','Fuel stores chemical energy. The oxidiser lets the reaction happen without taking oxygen from the air. Together they are the propellant. Different pairs make different exhaust gases, so the same mass can give a different push.','Try hydrogen, methane and kerosene. Each uses liquid oxygen here. The best choice for a whole rocket also depends on its tanks and its job.'],
    ['The exhaust matters as much as the heat.','An engine turns some of the gas’s thermal energy into directed motion. Hotter gas can help, but lighter gas molecules can also leave faster. That is why hydrogen can perform well even though hydrogen storage takes a lot of space.','Specific impulse, Isp, compares thrust with propellant flow using standard Earth gravity: Isp = F / (ṁg₀), measured in seconds. A higher value means more impulse from each kilogram, not necessarily more thrust from an engine of a given size. It does not change just because the engine travels to a world with different gravity.'],
    ['A useful model, with a deliberate boundary.','The nozzle calculation uses a perfect gas with a fixed heat-capacity ratio, γ, for each pair. A representative characteristic velocity, c*, summarises chamber gas behaviour. Real gases react and change composition as they expand.','Our broad mixture-response curves are illustrative, not chemical-equilibrium calculations or measured engine maps. They show trends without predicting a real engine. Real selection also balances density, storage temperature, reliability and cost.'],
  ]},
  pressure:{name:'Chamber pressure',tip:'Pressure is the gas pushing on the chamber walls. At the same throat size, more pressure sends more mass through each second. Values are absolute pressure; 1 bar is about Earth’s air pressure.',levels:[
    ['Gas pushing in every direction.','The chamber contains hot, crowded gas. Its pressure pushes on the walls and drives gas towards the nozzle. Raising the pressure usually gives more thrust, if the rest of the engine can cope.','Our slider goes to 350 bar: an illustrative upper limit for exploring high pressure. It is above the historical engines compared here, not a recommended setting for a real engine. A higher number does not automatically make a better rocket.'],
    ['Pressure buys flow—and brings demands.','With the same gas and throat area, the mass flowing out each second is roughly proportional to chamber pressure. Double the pressure and the model gives about twice the flow. The nozzle’s match to outside air changes too.','For perspective, NASA lists about 78 bar for the Saturn V F-1 and about 207 bar for the Shuttle main engine at its original rated condition. These are rounded historical references, not every version’s operating pressure. Real chambers also need cooling and strong materials.'],
    ['Separate chamber pressure from exhaust speed.','The choked-flow relation can be written ṁ = p꜀Aₜ/c*. Here ṁ means kilograms per second, p꜀ chamber pressure in pascals, Aₜ throat area in square metres and c* a gas-performance quantity in metres per second. At fixed gas conditions, doubling p꜀ doubles ṁ.','In vacuum, this ideal model’s specific impulse and exhaust speed depend on gas properties and expansion ratio, rather than directly on absolute pressure; thrust still increases with pressure. In air, pressure ratio matters. Real chemistry, heat loss, pumps and chamber mass complicate the story. The slider’s upper limit is a teaching choice, not an engine specification.'],
  ]},
  throat:{name:'Throat diameter',tip:'The throat is the narrowest part. This is a diameter, not an area: doubling it gives four times the area and roughly four times the flow at the same pressure. It does not make the exhaust four times faster.',levels:[
    ['The narrow neck.','Gas squeezes through the narrowest part of the nozzle: the throat. With enough pressure behind it, the gas reaches the local speed of sound there. A wider throat lets more gas through each second.','Try doubling the diameter while keeping pressure the same. The opening has four times the area, so much more propellant flows through.'],
    ['A flow control made of geometry.','At the throat the gas is “choked”: its speed is the local speed of sound. This does not mean the flow has stopped. It means the throat limits how much can pass for the chosen chamber conditions.','At fixed pressure, gas properties and expansion ratio, increasing throat area raises mass flow and thrust together. Specific impulse stays the same in this model. A real supply system may not be able to keep the pressure unchanged.'],
    ['Diameter and area are different levers.','Aₜ = πdₜ²/4. That square is the reason doubling diameter quadruples area. Combine this with ṁ = p꜀Aₜ/c* to predict how flow changes before touching the slider.','Mach number compares gas speed with the local speed of sound, which itself depends on temperature and gas properties. The throat is Mach 1; the expanding section can then accelerate the gas beyond Mach 1. This model assumes enough pressure to keep the throat choked.'],
  ]},
  expansion:{name:'Expansion ratio',tip:'Exit area divided by throat area. For circular openings, a ratio of 16 means four times the diameter, not sixteen. Auto for air matches exit pressure to sea-level air; Auto for vacuum uses the largest allowed bell because nozzle weight is omitted.',levels:[
    ['Why the nozzle opens out.','After the narrow throat, the nozzle gets wider. The very fast gas spreads out, cools and speeds up. Its pressure falls as more energy becomes forward-and-backward motion: gas backwards, rocket forwards.','Air presses on the exhaust outside the engine. A bell that suits space can be too wide for sea-level air. Try both Auto buttons and watch the shape change.'],
    ['Match the nozzle to its surroundings.','Expansion ratio is exit area divided by throat area. Ideally, in air, gas leaves at about the surrounding pressure. If its pressure is higher, it still has expansion to do outside the nozzle. If lower, the surrounding air squeezes it.','An extremely overexpanded flow can pull away from the nozzle wall. The amber warning marks a rough estimate of that separation. In vacuum there is no outside air pressure; more expansion helps, with diminishing returns. A larger real nozzle also weighs more.'],
    ['The pressure term is part of thrust.','F = ṁvₑ + (pₑ − pₐ)Aₑ. The first term is momentum carried out by the gas; the second comes from exit pressure compared with ambient pressure. Here vₑ is actual exhaust speed, distinct from effective exhaust speed F/ṁ.','For this ideal model in air, maximum performance occurs near pₑ = pₐ. Auto uses that pressure match, within the 1–200 area range. In vacuum a perfect, weightless nozzle has no finite best ratio: Auto selects the upper bound, 200. The separation estimate clips the useful nozzle where pressure falls to 40% of ambient. This is a rough teaching rule, not a universal threshold; it cannot predict shocks or sideways forces.'],
  ]},
  mixture:{name:'Oxidiser / fuel ratio',tip:'This is a mass ratio. O/F = 3 means 3 kg of oxidiser for each 1 kg of fuel—not three times the tank volume. Auto chooses the peak of an illustrative mixture curve, not a recipe for a real engine.',levels:[
    ['How much of each ingredient?','O/F means oxidiser mass divided by fuel mass. A ratio of 3 means three kilograms of oxidiser for each kilogram of fuel. It says nothing directly about the sizes of the tanks.','More oxidiser does not always mean more useful push. The balance changes the heat released and the gases that leave. Our smooth classroom curve lets you explore that idea.'],
    ['The hottest mix need not give the fastest exhaust.','Changing the mixture changes both temperature and the average mass of exhaust molecules. A mix with some extra fuel can produce lighter exhaust. Engines therefore do not necessarily aim for the exact chemical ratio that uses up every ingredient.','The Auto buttons choose the best specific impulse in this teaching model. Both choose the same mixture here because the model holds each pair’s gas behaviour fixed apart from a simple mixture penalty. Real chemistry can shift the best ratio with pressure and expansion.'],
    ['What the optimiser actually knows.','The model gives each pair a broad, smooth peak in c* as O/F changes. Thrust at a fixed chamber pressure and throat is largely set by pressure and geometry; varying c* changes mass flow and therefore impulse per kilogram. Auto selects the peak of that explicit approximation.','A real analysis calculates chemical equilibrium or frozen composition along the nozzle and considers cooling, stability, tank mass and the mission. Our peak is an illustrative reference, not a measured optimum or a prediction of a flight engine. The mass fractions are O/F ÷ (1 + O/F) for oxidiser and 1 ÷ (1 + O/F) for fuel.'],
  ]},
} as const;
export type NozzleTopic=keyof typeof NOZZLE_TOPICS;
